# Generated by Django 2.2.6 on 2019-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='model_name',
            field=models.CharField(max_length=40),
        ),
    ]
