# Generated by Django 2.2.6 on 2019-12-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191218_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='stores',
            field=models.ManyToManyField(to='main_app.Store'),
        ),
    ]
